### ISSUE TITLE
Doesn't work on Python 3.5.2

### ISSUE THREAD

**Issue by wxd** [pedrozudo/MathGenGraph#1]
Error message:
```
Traceback (most recent call last):
  File "mathgengraph/mathgengraph.py", line 5, in <module>
    from bs4 import BeautifulSoup
  File "/usr/lib/python3/dist-packages/bs4/__init__.py", line 30, in <module>
    from .builder import builder_registry, ParserRejectedMarkup
  File "/usr/lib/python3/dist-packages/bs4/builder/__init__.py", line 314, in <module>
    from . import _html5lib
  File "/usr/lib/python3/dist-packages/bs4/builder/_html5lib.py", line 70, in <module>
    class TreeBuilderForHtml5lib(html5lib.treebuilders._base.TreeBuilder):
AttributeError: module 'html5lib.treebuilders' has no attribute '_base'
```

**Comment by pedrozudo** [comment]
This stackoverflow thread might help you resolve the issue. Otherwise you can always use python 3.6.
